### ISSUE TITLE
Feature Request: Increase ore presence / multicraft electronics

### ISSUE THREAD

**Issue by dan-hale** [wafflecomposite/linkarus#1]
I'd love a mod that saves me some time crafting electronics. I'd play this game alot more if I knew I didn't have to spend 2-4 hours grinding. It's very frustrating when I only have a few hours to play this game a week.

When crafting one electronic, it should give 5 instead of just 1 - or, the ores needed to make electronics should be in larger quantities in caves. 

Please please make this happen!!

**Comment by wafflecomposite** [comment]
Good news, your wish will come true soon enough.
Bad news, the file I have to edit for this contains all the recipes, so this type of mod will only be compatible with a specific version of the game, and is sure to break something on newer versions. 
I will have to update this mod after every game update, you will have to delete the old mod, and wait for the new one.

**Comment by dan-hale** [comment]
I'd love to help you beta test, this mod won't come soon enough for me!

Maybe there is a way to inject modifications into the recipes file so you don't have to rewrite the entire file?

Or maybe you can provide a seperate file with the .pak so you only need to update the version file and not the whole .pak?

**Comment by wafflecomposite** [comment]
> Maybe there is a way to inject modifications into the recipes file so you don't have to rewrite the entire file?

I really hope so, that would be a dream, but so far I can't figure it out.

> Or maybe you can provide a seperate file with the .pak so you only need to update the version file and not the whole .pak?

whole .pak of mod will only contain single file with recipes, this is as optimized as it gets at the moment. 

I'm also in the middle of writing a tool that will automatically rebuild a mods for the game after the updates

**Comment by dan-hale** [comment]
Very cool. I'm happy to help if there's anything I can do. I'm a full stack node developer, but I have some experience in unreal and other languages.

I could make a command line tool that does just about anything, make complete desktop apps with a GUI with electron. I suspect that could help.

Depending on how the game files are stored, I can probably make a tool that does this injection and generates a .pak automatically in the kids directory.

Do you have any resources you could link for how the mods folder works? Im new to this way of unreal mods.
________________________________

**Comment by wafflecomposite** [comment]
@Nuzzlet Since the whole Icarus modding scene consist of me starting to get familiar with UE4 mods two days ago, another guy from reddit, and the two people who made cheat engine tables, you can imagine that we could definitely use some help, but it's unclear when and what. From what you describe, yeah, some kind of GUI mod manager and/or mod generator could definitely come in handy.

I recommend that you check out guides and tools from Deep Rock Galactic (another UE4 game) modding discord https://discord.gg/gUw32ayWGt and general UE4 modding discord https://discord.gg/zVvsE9mEEa , atleast it's how i started.

Goal, in general, is to unpack game .pak, modify what you need, delete anything else, pack modified files back to .pak, name it so the name ends with "_P" for whatever reason and put it somewhere in the \Content\Paks\ directory where it will be loaded automatically.

I will publish tools that I use, python scripts and a few notes in this repo sources as soon as I can actually make it work correctly.

**Comment by dan-hale** [comment]
What isn't working correctly atm? I can definitely make a GUI, and I can write along with it operations like unpacking the .pak, making changes, then repacking it programatically.

What are you currently stuck on?

Can the .pak be unpacked with 7zip?

Where is the main game.pak?

Does the /mods folder simply overwite the oak content of the main .pals upon game load?
________________________________

**Comment by dan-hale** [comment]
Also, it sounds like it would be helpful to start a discord for this. Since you're the pioneer, it would be right for you to own it? If you post a link I'll join and chat with you on there. We could have a private category for the developer role so we can organize people like me to help with whatever we can.
________________________________

**Comment by wafflecomposite** [comment]
What we need most is to figure out how the hell those .json files from data.pak like recipes is loaded in the first place and how we can intervene in this process and partially modify them from multiple mods.

.pak should be unpacked using UnrealPak for 4.26 engine version. There is no "main" game.pak, anything .pak you can find is a bunch of random game files. 
.pak with recipes and other funny things is in the data.pak that for unknown reasons lies in "Data" folder instead of "Paks"

I plan to start discord a little later. I applaud your interest in taking part, but for the time being please do your own research as I still need time to get to grips with the UE4 modding basics and document some findings and best practices

**Comment by wafflecomposite** [comment]
On the original topic: there is update coming, It's already on experimental branch, and it's supposed to change T4 resource balance quite heavily https://www.reddit.com/r/ICARUS/comments/se7ols/experimental_branch_patch_notes_from_today/

**Comment by dan-hale** [comment]
Thank you!

I'm thinking it would be possible to write a program that unpaks data.pak, makes changes to the JSON as we desire, then re-paks and replaces the original file.

I was able to successfully unpack, and change the contents of the game settings, but i'm a little confused about how to repack with the command line tool...what command did you use to make your files?

I understand what you are saying about intercepting the process getting the .json, especially because certainly rocketwerkz is going to encrypt the .paks when they realize we are doing this.

**Comment by dan-hale** [comment]
https://stackoverflow.com/questions/54290544/unreal-engine-4-what-is-correct-way-to-pak-files-load-mount-them-and-load-asse

Might have some useful information.

**Comment by dan-hale** [comment]
What is the mount point of these game.pak files?

**Comment by wafflecomposite** [comment]
New mod that tweaks crafting recipes including electronics https://github.com/wafflecomposite/linkarus/releases/tag/craftsman_V1_build1.1.1.90762

Discord server opened https://discord.com/invite/2UrWDXjxUk

You can get mounting point of every individual .pak with `UnrealPak <PakFilename> -List` command, mounting point will be listed at the top of output.
Except for `data.pak` specifically, mounting point for `data.pak` should actually be `..\..\..\Icarus\Content\data\*.*`

**Comment by wafflecomposite** [comment]
I believe we are done with the actual topic of the electronics price, so I'm closing this issue
